 image:
      name: docker/compose:latest
      entrypoint: ["/bin/sh", "-c"]

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
  - docker info

stages: [ deploy ]

deploy_content: 
    stage: deploy  
    script:  
        - docker-compose build
        
