image: tmaier/docker-compose:latest

services:
  - docker:19.03.12-dind

before_script:
  - docker info

stages: [ deploy ]

deploy_content: 
    stage: deploy  
    script:  
        - docker-compose build
