image:
     name: docker

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

stages: [ build ]

build_content: 
    stage: build  
    script:  
        - docker-compose build
