image:
     name: docker/compose:latest
     entrypoint: ["/bin/sh", "-c"]

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

stages: [ deploy ]

deploy_content: 
    stage: deploy  
    script:  
        - docker-compose build
        
