image: docker:19.03.12

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install docker-compose


  
stages: [ build ]

build_content: 
    stage: build  
    script:  
        - docker-compose -f docker-compose.yml build
