image: docker:19

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19-dind

before_script:
  - docker info

stages: [ deploy ]

deploy_content: 
    stage: deploy  
    script:  
        - docker-compose build
