version: '3.8'
services:
  figura:
    build: ./Figura
    container_name:  Figura_1.0
    ports:
      - 8888:8888
  discovery:
    build: ./Discovery
    container_name: Discovery_1.0
    ports:
      - 8100:8100
    depends_on:
      - figura
