spring:
   application:
      name: Chef
server:
   port: 8100
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
         preferIpAddress: true
      fetch-registry: false