spring:
  application:
    name: Discovery
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 8761
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false