server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: Chef
        uri: http://localhost:8100/
        predicates:
        - Path=/Chef/**
      - id: Figura
        uri: http://localhost:8888/
        predicates:
        - Path=/Figura/**