server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: Chef
        uri: http://localhost:8100/
        predicates:
        - Path=/applications/**
      - id: Ducere
        uri: http://localhost:9000/
        predicates:
        - Path=/actor/**
      - id: Sham
        uri: http://localhost:8088/
        predicates:
        - Path=/movie/**
      - id: Discovery
        uri: http://localhost:8761/
        predicates:
        - Path=/**
  boot:
    admin:
      client:
        url: http://localhost:8100
  main:
    web-application-type: reactive

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
         preferIpAddress: true
      fetch-registry: false

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: CÇ£g
  resource: Sentinel
  ssl-required: all
  public-client: true
  securityConstraints[0]:
    - authRoles[0]: user
      securityCollections[0]:
        - name: Sentinel
          patterns[0]: /applications

