spring:
   application:
      name: Sham
   boot:
    admin:
      client:
        url: http://localhost:8100
server:
   port: 8088
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
         preferIpAddress: true
      fetch-registry: false
