server:
  port: 8888
spring:
  application:
      name: Figura
  cloud:
      config:
        server:
            git:
              uri: https://github.com/MelekZmerli/microservices
              search-paths: service-configs
  profiles:
      active: default
